Update env.yaml

diff --git a/.github/workflows/env.yaml b/.github/workflows/env.yaml
--- a/.github/workflows/env.yaml
+++ b/.github/workflows/env.yaml
@@ -9,6 +9,7 @@ on:
         default: 'dev=blue'
       app_name:
         required: false  
+        default: 'nginx, old'
   # schedule:
   #   - cron: '*/2 * * * *'
 
@@ -85,6 +86,12 @@ jobs:
           printenv | grep -E 'domain|rg'
 
       - name: Run task env prod
-        if: ${{github.event.inputs.env == 'prod'}}
         run: |
-          echo "env is set to prod"
+          IFS=',' read -r -a app_names <<< "${{ github.event.inputs.app_name }}"
+          if [ ${#app_names[@]} -eq 0 ]; then
+            echo "Error: app_name list cannot be empty"
+            exit 1
+          fi
+
+          echo "App names provided: ${app_names[@]}"
+
